// import {
//   kid1a,
//   kid1b,
//   kid1c,
//   kid1d,
//   kid2a,
//   kid2b,
//   kid2c,
//   kid2d,
//   kid3a,
//   kid3b,
//   kid3c,
//   kid3d,
//   kid4a,
//   kid4b,
//   kid4c,
//   kid4d,
//   man1a,
//   man1b,
//   man1c,
//   man1d,
//   man2a,
//   man2b,
//   man2c,
//   man2d,
//   man3a,
//   man3b,
//   man3c,
//   man3d,
//   man4a,
//   man4b,
//   man4c,
//   man4d,
//   woman1a,
//   woman1b,
//   woman1c,
//   woman1d,
//   woman2a,
//   woman2b,
//   woman2c,
//   woman2d,
//   woman3a,
//   woman3b,
//   woman3c,
//   woman3d,
//   woman4a,
//   woman4b,
//   woman4c,
//   woman4d,
// } from "@/public/img/data";
// import { Product } from "@/types/product";

// export const products: Product[] = [
//   {
//     id: "kid-1",
//     name: "Kids Casual Wear 1",
//     price: 4500,
//     desc: "Comfortable casual outfit for kids, suitable for everyday wear.",
//     images: [kid1a, kid1b, kid1c, kid1d],
//   },
//   {
//     id: "kid-2",
//     name: "Kids Casual Wear 2",
//     price: 4800,
//     desc: "Stylish kids clothing made with soft and breathable fabric.",
//     images: [kid2a, kid2b, kid2c, kid2d],
//   },
//   {
//     id: "kid-3",
//     name: "Kids Casual Wear 3",
//     price: 5000,
//     desc: "Modern kids outfit designed for comfort and durability.",
//     images: [kid3a, kid3b, kid3c, kid3d],
//   },
//   {
//     id: "kid-4",
//     name: "Kids Casual Wear 4",
//     price: 5200,
//     desc: "Trendy kids fashion set suitable for outings and play.",
//     images: [kid4a, kid4b, kid4c, kid4d],
//   },

//   {
//     id: "man-1",
//     name: "Men Classic Outfit 1",
//     price: 12000,
//     desc: "Classic men’s wear with a clean and stylish finish.",
//     images: [man1a, man1b, man1c, man1d],
//   },
//   {
//     id: "man-2",
//     name: "Men Classic Outfit 2",
//     price: 13500,
//     desc: "Comfortable men’s outfit perfect for casual and semi-formal use.",
//     images: [man2a, man2b, man2c, man2d],
//   },
//   {
//     id: "man-3",
//     name: "Men Classic Outfit 3",
//     price: 15000,
//     desc: "High-quality men’s fashion wear with premium stitching.",
//     images: [man3a, man3b, man3c, man3d],
//   },
//   {
//     id: "man-4",
//     name: "Men Classic Outfit 4",
//     price: 16500,
//     desc: "Modern men’s wear designed for style and comfort.",
//     images: [man4a, man4b, man4c, man4d],
//   },

//   {
//     id: "woman-1",
//     name: "Women Fashion Set 1",
//     price: 14000,
//     desc: "Elegant women’s fashion set suitable for all occasions.",
//     images: [woman1a, woman1b, woman1c, woman1d],
//   },
//   {
//     id: "woman-2",
//     name: "Women Fashion Set 2",
//     price: 15500,
//     desc: "Stylish women’s outfit with a modern design.",
//     images: [woman2a, woman2b, woman2c, woman2d],
//   },
//   {
//     id: "woman-3",
//     name: "Women Fashion Set 3",
//     price: 17000,
//     desc: "Premium women’s wear made with high-quality materials.",
//     images: [woman3a, woman3b, woman3c, woman3d],
//   },
//   {
//     id: "woman-4",
//     name: "Women Fashion Set 4",
//     price: 18500,
//     desc: "Trendy women’s fashion perfect for outings and events.",
//     images: [woman4a, woman4b, woman4c, woman4d],
//   },
// ];

import { Product } from "@/types/product";

export const products: Product[] = [
  // Kids
  {
    id: "kid-1",
    name: "Kids Casual Wear 1",
    price: 4500,
    desc: "Comfortable casual outfit for kids, suitable for everyday wear.",
    images: [
      "/img/nikekid1a.avif",
      "/img/kid1b.avif",
      "/img/kid1c.avif",
      "/img/kid1d.avif",
    ],
  },
  {
    id: "kid-2",
    name: "Kids Casual Wear 2",
    price: 4800,
    desc: "Stylish kids clothing made with soft and breathable fabric.",
    images: [
      "/img/kid2a.avif",
      "/img/kid2b.avif",
      "/img/kid2c.avif",
      "/img/kid2d.avif",
    ],
  },
  {
    id: "kid-3",
    name: "Kids Casual Wear 3",
    price: 5000,
    desc: "Modern kids outfit designed for comfort and durability.",
    images: [
      "/img/kid3a.avif",
      "/img/kid3b.avif",
      "/img/kid3c.avif",
      "/img/kid3d.avif",
    ],
  },
  {
    id: "kid-4",
    name: "Kids Casual Wear 4",
    price: 5200,
    desc: "Trendy kids fashion set suitable for outings and play.",
    images: [
      "/img/kid4a.avif",
      "/img/kid4b.avif",
      "/img/kid4c.avif",
      "/img/kid4d.avif",
    ],
  },

  // Men
  {
    id: "man-1",
    name: "Men Classic Outfit 1",
    price: 12000,
    desc: "Classic men’s wear with a clean and stylish finish.",
    images: [
      "/img/man1a.avif",
      "/img/man1b.avif",
      "/img/man1c.avif",
      "/img/man1d.avif",
    ],
  },
  {
    id: "man-2",
    name: "Men Classic Outfit 2",
    price: 13500,
    desc: "Comfortable men’s outfit perfect for casual and semi-formal use.",
    images: [
      "/img/man2a.avif",
      "/img/man2b.avif",
      "/img/man2c.avif",
      "/img/man2d.avif",
    ],
  },
  {
    id: "man-3",
    name: "Men Classic Outfit 3",
    price: 15000,
    desc: "High-quality men’s fashion wear with premium stitching.",
    images: [
      "/img/man3a.avif",
      "/img/man3b.avif",
      "/img/man3c.avif",
      "/img/man3d.avif",
    ],
  },
  {
    id: "man-4",
    name: "Men Classic Outfit 4",
    price: 16500,
    desc: "Modern men’s wear designed for style and comfort.",
    images: [
      "/img/man4a.avif",
      "/img/man4b.avif",
      "/img/man4c.avif",
      "/img/man4d.avif",
    ],
  },

  // Women
  {
    id: "woman-1",
    name: "Women Fashion Set 1",
    price: 14000,
    desc: "Elegant women’s fashion set suitable for all occasions.",
    images: [
      "/img/woman1a.avif",
      "/img/woman1b.avif",
      "/img/woman1c.avif",
      "/img/woman1d.avif",
    ],
  },
  {
    id: "woman-2",
    name: "Women Fashion Set 2",
    price: 15500,
    desc: "Stylish women’s outfit with a modern design.",
    images: ["/img/woman2a.avif", "/img/woman2b.avif", "/img/woman2c.avif"],
  },
  {
    id: "woman-3",
    name: "Women Fashion Set 3",
    price: 17000,
    desc: "Premium women’s wear made with high-quality materials.",
    images: [
      "/img/woman3a.avif",
      "/img/woman3b.avif",
      "/img/woman3c.avif",
      "/img/woman3d.avif",
    ],
  },
  {
    id: "woman-4",
    name: "Women Fashion Set 4",
    price: 18500,
    desc: "Trendy women’s fashion perfect for outings and events.",
    images: [
      "/img/woman4a.avif",
      "/img/woman4b.avif",
      "/img/woman4c.avif",
      "/img/woman4d.avif",
    ],
  },
];
